sudo: false
dist: trusty
language: node_js
node_js:
- '8'
notifications:
  email: false
addons:
  firefox: '56.0'
  chrome: stable
branch:
  only:
  - master
install:
- travis_retry npm install
- npm i -g greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- jdk_switcher use oraclejdk8
- npm run mockserver > /dev/null 2>&1 &
- npm run webdriver > /dev/null 2>&1 &
- sleep 15
script:
- npm test
after_script:
- greenkeeper-lockfile-upload
before_deploy:
- npm run build
deploy:
  provider: npm
  email: j.andrichak@rackspace.com
  skip_cleanup: true
  api_key:
    secure: YC8g87SjPI1Mx9KEQrhx+NGRUtsnXt1LJVo0lyILIy17ja6Sx2IyR7eelIdoYbDcuxB7wNzM8Gte/fJV01Xi8rpLTAR4EiL/iGwEywCx8x9TXbJhzx9YxGd+USTvgzuvC+hJmoY7bSsodk0LB0fwdHQFTf1vbFxkWz/jqt9y4HuF3ZCfT1YtJEuHIiMcE+nwraBBdw4AAUFgYddWxWeZbz/IKWFxEG+4YrrZrrrEoJCYOZx1yoNTgq83lW7jNTCYlE4wyybL0wbm8ROGjGKzZoM2W9giG0rJBn2gQRroJryubthC3Ty48i1/smTWVY/XSVKfmPeD87BXg2H5dv7HHHJnDj72/q78AQpNThE9yTatiy8XF4muURhxiVTV4yvy2mj9ueAiTEu5XsZb/2BFqrxb+pOrVySh1j+bUawGGMbrkBxO9c0ilvZqGONj+Ku2ahMSOgm1kl0bJytcbqRoC35XE2qQSFK9rSodrb7u1LQl8LaOJl3vI82KF1Pc+7Um04lkoGF6XBhRGPuOX49J1WqoHoqYdGYOqPB/ii5JF7YehfPMd3sZoa1V4l4kKrCqHGPQ3WnaGlKfTxrdm1cDuIs0QoS7X761dG490RExjE2X56KrFPfz4Nl4PsVMVl+lfPXpEvObxjaI5bA4/oL63aKJKVKuq2iMrENlfluYvp4=
  on:
    condition: "-z $TRAVIS_TAG"
    branch:
    - master
    repo: rackerlabs/snappit-visual-regression
